// Artifact library — Jazz demo.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q2 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-05-30',
    summary: 'Full Q2 Strategy-to-Action: ISP pillars, MO coverage, prioritised insights (AI1–AI5), proposed actions (A1–A9), social signal velocity summary, Gap Radar suggestions, and LP6 KOL digital alignment rationale.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'X / LinkedIn social listening', 'ASCO 2025 congress debriefs', 'PubMed'],
    sizeLabel: '2.6 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'ASCO 2025 Debrief — Modeyso & Ziihera Signal Analysis',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-06-03',
    summary: 'Synthesized read on H3 K27M DMG and HER2+ GEC/BTC scientific themes at ASCO 2025 — social amplification map, KOL post-congress narrative shifts, Enhertu vs Ziihera share-of-voice, and recommended MSL response actions.',
    dataSources: ['ASCO 2025 abstracts', 'Session transcripts', 'X / LinkedIn monitoring', 'KOL post-congress commentary'],
    sizeLabel: '2.1 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'KOL Public–Private Alignment Report — June 2026',
    type: 'pdf',
    agent: 'LUCA',
    taskType: 'KOL Intelligence Report',
    dateCreated: '2026-06-04',
    summary: 'Alignment scoring for 17 Jazz portfolio KOLs across public (X, LinkedIn, Medscape) and private (MSL interaction) channels. Flags 3 divergence cases for immediate action. Includes recommended scientific exchange briefs for Dr. Merchant and Dr. Venkatramani.',
    dataSources: ['MSL interaction logs', 'X / LinkedIn monitoring', 'Medscape / NeurologyLive coverage', 'PubMed publication tracking'],
    sizeLabel: '1.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'Ziihera Pre-Launch Landscape — HER2+ GEC Share-of-Voice Baseline',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Competitive Intelligence Report',
    dateCreated: '2026-05-15',
    summary: 'Baseline share-of-voice, sentiment NPS, and HCP awareness metrics for zanidatamab vs Enhertu in HER2+ GEC/BTC — establishing the measurement framework to track Ziihera launch impact over the next 12 months.',
    dataSources: ['X / LinkedIn social listening (n=823 posts)', 'Congress abstract analysis', 'MSL interaction logs', 'KOL publication monitoring'],
    sizeLabel: '1.9 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'H3 K27M Testing Barrier Field Survey — Community Oncology',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Field Insight Synthesis',
    dateCreated: '2026-05-10',
    summary: 'Aggregated analysis of MSL-reported and social-channel-detected H3 K27M testing barriers across 34 community oncology practices. Key findings: 44% not reflexing on midline glioma biopsies; mean diagnostic delay 5.3 weeks; top barrier: institution-level protocol gaps, not physician awareness.',
    dataSources: ['MSL field reports', 'LinkedIn community monitoring', 'OncologyTribe group posts', 'Pathology network survey'],
    sizeLabel: '1.2 MB',
    provenance: 'synthesized',
  },
];
