// Actionable insights — Jazz demo.
// Social media sourcing is the headline pattern throughout.
// sourceInsights includes social posts alongside MSL and ad-board entries.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'KOL public–private alignment gap on pediatric Modeyso data',
    priority: 'High',
    lpRefs: ['LP3'], moRefs: ['MO1', 'MO3'],
    recurrence: 4,
    recency: '2026-05',
    summary: 'NOVA\'s cross-channel alignment engine detected that three top-tier neuro-oncology KOLs express higher confidence in Modeyso on private MSL calls than in their public social media and congress statements. The gap is widest around pediatric dosing — where RWE is thinnest. This misalignment is creating a trust vacuum that competitors are beginning to exploit.',
    sourceInsights: [
      { type: 'X / Social Media', role: 'Dr. S. Merchant, Neuro-oncologist', location: 'X (@SMerchantMD)', quote: 'Modeyso RWE in pediatric H3K27M is promising but we need longer follow-up before I\'d change my practice in <18s. Still watching.', date: '2026-04-28' },
      { type: 'MSL interaction', role: 'Dr. S. Merchant, Neuro-oncologist', location: 'Boston, MA', quote: 'The 18-month follow-up data from Jazz actually addresses a lot of my questions — I\'m already adjusting my approach for refractory pediatric cases.', date: '2026-04-21' },
      { type: 'LinkedIn', role: 'Dr. R. Venkatramani, Pediatric Oncologist', location: 'LinkedIn', quote: 'Hoping ASCO 2025 gives us the pediatric DMG subgroup data we\'ve all been waiting for. Evidence gaps are real.', date: '2026-05-02' },
      { type: 'Ad board', role: 'Dr. R. Venkatramani', location: 'Virtual', quote: 'If Jazz publishes the pediatric cohort data I\'ve seen in draft, this conversation changes immediately.', date: '2026-04-10' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.91,
    provenance: 'synthesized',
    socialSignalVelocity: '+74% in 30 days',
  },
  {
    id: 'AI2',
    title: 'GI oncology skepticism toward bispecific HER2 mechanism is socially amplified',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'A cluster of 5 influential GI KOLs on X is driving skepticism about zanidatamab\'s differentiated profile vs Enhertu in HER2+ GEC. Combined follower reach: 47K. NOVA tracked 340 posts; 44% express skepticism. This narrative is reaching community oncologists and could slow Ziihera pre-launch perception building if not addressed.',
    sourceInsights: [
      { type: 'X / Social Media', role: 'Dr. T. Yamaoka, GI Oncologist', location: 'X (@TYamaoka_GI)', quote: 'Before the bispecific hype, I\'d want to see a direct comparison with T-DXd in first-line HER2+ GEC. Mechanism is interesting. Survival curves are what matter.', date: '2026-05-01' },
      { type: 'X / Social Media', role: 'Dr. M. Chávez, Medical Oncologist', location: 'X (@MChavezOncMD)', quote: 'The zanidatamab bispecific story is compelling on paper. Looking forward to seeing the GEC survival readout at ASCO.', date: '2026-04-29' },
      { type: 'Congress debrief', role: 'GI oncologist', location: 'ASCO 2025', quote: 'My question after the poster: is this differentiated enough from the ADC data? That\'s what my tumor board will ask.', date: '2026-05-31' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.86,
    provenance: 'synthesized',
    socialSignalVelocity: '+54% in 45 days',
  },
  {
    id: 'AI3',
    title: 'H3 K27M testing barriers surfaced in community oncology social channels',
    priority: 'High',
    lpRefs: ['LP4'], moRefs: ['MO4'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'Community oncologists are openly discussing H3 K27M testing access gaps in oncology LinkedIn groups and the @OncologyTribe community. Key barriers: institutional lab turnaround times, reimbursement for FFPE molecular testing, and unfamiliarity with which patients to test. This conversation is happening without Jazz MA presence.',
    sourceInsights: [
      { type: 'LinkedIn Community', role: 'Community Oncologist', location: 'LinkedIn — OncologyTribe Group', quote: 'How long is everyone waiting for H3 K27M results? We\'re at 3 weeks which feels too slow when the patient is symptomatic.', date: '2026-05-03' },
      { type: 'X / Social Media', role: 'Neuro-oncology fellow', location: 'X (@NeuroOncoFellow)', quote: 'Just found out our institution doesn\'t reflex to H3 K27M on midline glioma biopsy. Is this others\' experience too?', date: '2026-04-25' },
      { type: 'MSL interaction', role: 'Community oncologist', location: 'Dallas, TX', quote: 'I didn\'t know I was supposed to request H3 K27M specifically — my path lab wasn\'t doing it automatically.', date: '2026-05-08' },
    ],
    status: 'Validated',
    confidenceScore: 0.83,
    provenance: 'synthesized',
    socialSignalVelocity: '+41% in 30 days',
  },
  {
    id: 'AI4',
    title: 'Patient advocacy community amplifying Modeyso access concerns',
    priority: 'Medium',
    lpRefs: ['LP5'], moRefs: ['MO5'],
    recurrence: 2,
    recency: '2026-04',
    summary: 'NBTS and PBTF Facebook communities (combined ~85K members) have surfaced 12 caregiver narratives about difficulty accessing Modeyso at community centers. Families are navigating travel burden to academic centers. Payer prior authorization requirements cited as a secondary barrier. No formal Jazz MA response present in these threads.',
    sourceInsights: [
      { type: 'Facebook / Patient Community', role: 'Caregiver — parent of pediatric DMG patient', location: 'NBTS Community Facebook Group', quote: 'We drove 4 hours to get to a center that would prescribe dordaviprone. Worth it, but it shouldn\'t be this hard.', date: '2026-04-18' },
      { type: 'Facebook / Patient Community', role: 'Adult DMG patient', location: 'Pediatric Brain Tumor Foundation Group', quote: 'Insurance denied the first PA for Modeyso — said it wasn\'t "medically necessary." My oncologist had to appeal twice.', date: '2026-04-22' },
    ],
    status: 'Triaged',
    confidenceScore: 0.74,
    provenance: 'synthesized',
    socialSignalVelocity: '+29% in 60 days',
  },
  {
    id: 'AI5',
    title: 'Ziihera social awareness significantly trails Enhertu among HER2+ community',
    priority: 'Medium',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 2,
    recency: '2026-05',
    summary: 'Share-of-voice analysis across X and LinkedIn shows zanidatamab at 41% mention frequency vs Enhertu at 67% in HER2+ GEC/BTC discussions. Favorable sentiment for zanidatamab is high (74%) but awareness is the constraint — Ziihera is not yet a reflex name for community GI oncologists.',
    sourceInsights: [
      { type: 'Social Listening Aggregate', role: 'NOVA Signal Engine', location: 'X + LinkedIn + ResearchGate', quote: 'Zanidatamab mentioned in 41% of HER2+ GEC discussions (n=823 posts). Bispecific mechanism cited positively in 74% of those. Awareness gap vs Enhertu: 26 percentage points.', date: '2026-05-10' },
      { type: 'X / Social Media', role: 'GI Oncology Fellow', location: 'X', quote: 'ASCO session on zanidatamab was eye-opening — I hadn\'t followed the bispecific data closely. Starting to understand the rationale.', date: '2026-06-01' },
    ],
    status: 'Validated',
    confidenceScore: 0.78,
    provenance: 'synthesized',
    socialSignalVelocity: '+38% in 30 days',
  },
];
