// KOL roster — Jazz demo.
// 17 real, publicly-verified KOLs across Modeyso (H3 K27M DMG) and Ziihera (HER2+ GEA/BTC).
// Sources: PubMed, institutional profiles, clinical trial registries, society records.

export const KOL_DATA = [
  {
    id: 'kol-1',
    name: 'Isabel Arrillaga-Romany',
    institution: 'Massachusetts General Hospital / Harvard Medical School',
    city: 'Boston',
    country: 'USA',
    region: 'North America',
    specialty: 'Neuro-Oncology',
    influenceScore: 97,
    engagementTier: 'Tier 1',
    productAlignment: ['modeyso'],
    recentInteractions: 11,
    publications: 80,
    focusAreas: ['H3 K27M-mutant DMG', 'Dordaviprone Clinical Trials', 'ACTION Phase 3 PI', 'Rare Neuro-Oncology'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Engage as national scientific anchor and advisory board lead; her JCO 2024 lead authorship and ACTION Phase 3 PI role make her the most credible external voice on Modeyso\'s clinical evidence package.',
    email: 'iarrillaga@mgh.harvard.edu',
  },
  {
    id: 'kol-2',
    name: 'Patrick Y. Wen',
    institution: 'Dana-Farber Cancer Institute / Harvard Medical School',
    city: 'Boston',
    country: 'USA',
    region: 'North America',
    specialty: 'Neuro-Oncology',
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['modeyso'],
    recentInteractions: 9,
    publications: 500,
    focusAreas: ['Adult Glioma Clinical Trials', 'RANO Response Criteria', 'SNO Leadership', 'ACTION Trial'],
    conferenceAppearances: 12,
    recommendedStrategy: 'Leverage for global advisory boards and high-visibility publications; his Neuro-Oncology editorial role and former SNO presidency make him a key gatekeeper for field-defining Modeyso messaging.',
    email: 'pwen@partners.org',
  },
  {
    id: 'kol-3',
    name: 'Michelle Monje',
    institution: 'Stanford University / Howard Hughes Medical Institute',
    city: 'Stanford',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric Neuro-Oncology',
    influenceScore: 95,
    engagementTier: 'Tier 1',
    productAlignment: ['modeyso'],
    recentInteractions: 6,
    publications: 200,
    focusAreas: ['DMG Biology & Mechanism', 'GD2 CAR-T in DIPG', 'H3 K27M Spatial Transcriptomics', 'Combination Approaches'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Engage as thought leadership partner for mechanism of action symposia and white papers on next-step Modeyso combination strategies; MacArthur Fellow and National Academy of Medicine member.',
    email: 'mmonje@stanford.edu',
  },
  {
    id: 'kol-4',
    name: 'Sabine Mueller',
    institution: 'UCSF Benioff Children\'s Hospital / UCSF Brain Tumor Center',
    city: 'San Francisco',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric Neuro-Oncology',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['modeyso'],
    recentInteractions: 10,
    publications: 150,
    focusAreas: ['Pediatric DMG Clinical Trials', 'H3 K27M cfDNA Response Biomarker', 'ONC201 Dose-Escalation', 'Liquid Biopsy in DMG'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Partner on biomarker and companion diagnostics strategy; her cfDNA tracking work is directly relevant to Modeyso response monitoring and label extensions.',
    email: 'sabine.mueller@ucsf.edu',
  },
  {
    id: 'kol-5',
    name: 'Andrew B. Lassman',
    institution: 'Columbia University / Herbert Irving Comprehensive Cancer Center',
    city: 'New York',
    country: 'USA',
    region: 'North America',
    specialty: 'Neuro-Oncology',
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['modeyso'],
    recentInteractions: 8,
    publications: 150,
    focusAreas: ['Phase II ONC201 in Adult HGG', 'ACTION Trial Co-author', 'RANO 2.0 Endpoint Methodology', 'Novel Therapeutics in Adult Glioma'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Engage as primary adult DMG advisory board member; his RANO 2.0 leadership makes him a key partner for endpoint discussions in Modeyso label expansion planning.',
    email: 'abl9@cumc.columbia.edu',
  },
  {
    id: 'kol-6',
    name: 'Martin J. van den Bent',
    institution: 'Erasmus MC Cancer Center',
    city: 'Rotterdam',
    country: 'Netherlands',
    region: 'Europe',
    specialty: 'Neuro-Oncology',
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['modeyso'],
    recentInteractions: 7,
    publications: 400,
    focusAreas: ['EORTC Brain Tumor Group Leadership', 'European Real-World ONC201 Data', 'Glioma Standards of Care', 'EANO Leadership'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Engage as European medical affairs anchor; essential for EMA regulatory filings; his EANO and EORTC roles make him the key opinion multiplier across European neuro-oncology societies.',
    email: 'm.vandenbent@erasmusmc.nl',
  },
  {
    id: 'kol-7',
    name: 'Carl Koschmann',
    institution: 'University of Michigan / C.S. Mott Children\'s Hospital',
    city: 'Ann Arbor',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric Neuro-Oncology',
    influenceScore: 83,
    engagementTier: 'Tier 2',
    productAlignment: ['modeyso'],
    recentInteractions: 9,
    publications: 100,
    focusAreas: ['Pediatric DMG Precision Medicine', 'ATRX Mutation Biology', 'ONC201 Pediatric PK/Safety', 'Molecular Driver Characterization'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Engage for pediatric medical education programs and speaker bureau; Michigan Medicine platform reaches community oncologists in the Midwest managing real-world DMG patients.',
    email: 'koschmann@med.umich.edu',
  },
  {
    id: 'kol-8',
    name: 'Susan L. McGovern',
    institution: 'MD Anderson Cancer Center',
    city: 'Houston',
    country: 'USA',
    region: 'North America',
    specialty: 'Radiation Oncology',
    influenceScore: 80,
    engagementTier: 'Tier 2',
    productAlignment: ['modeyso'],
    recentInteractions: 6,
    publications: 80,
    focusAreas: ['Radiation + Systemic Therapy in DMG', 'ACTION Trial Co-author', 'Pediatric CNS Proton Therapy', 'Post-RT Modeyso Maintenance'],
    conferenceAppearances: 6,
    recommendedStrategy: 'Engage for multidisciplinary medical education framing Modeyso as post-radiation systemic maintenance; unique radiation oncology perspective addresses a gap in current MSL coverage.',
    email: 'smcgovern@mdanderson.org',
  },
  {
    id: 'kol-9',
    name: 'Burt Nabors',
    institution: 'University of Alabama at Birmingham',
    city: 'Birmingham',
    country: 'USA',
    region: 'North America',
    specialty: 'Neuro-Oncology',
    influenceScore: 79,
    engagementTier: 'Tier 2',
    productAlignment: ['modeyso'],
    recentInteractions: 7,
    publications: 150,
    focusAreas: ['ACTION Trial Co-author', 'NCI Cooperative Group Trials', 'Emerging Targeted Therapy in Glioma', 'Southeast US Community Reach'],
    conferenceAppearances: 6,
    recommendedStrategy: 'Engage for regional medical affairs programs; UAB platform reaches community oncologists in the Southeast who will manage the majority of real-world DMG patients.',
    email: 'bnabors@uabmc.edu',
  },
  {
    id: 'kol-10',
    name: 'Yelena Y. Janjigian',
    institution: 'Memorial Sloan Kettering Cancer Center / Weill Cornell Medical College',
    city: 'New York',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['ziihera'],
    recentInteractions: 8,
    publications: 200,
    focusAreas: ['HER2+ Gastric/GEJ Cancer', 'KEYNOTE-811 Trial Lead', 'CheckMate 649', 'HER2 Resistance Mechanisms'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Engage as primary advisory board member for the GEA indication; KEYNOTE-811 prominence ensures she will be a defining voice in how clinicians position Ziihera vs trastuzumab-based regimens.',
    email: 'janjigiy@mskcc.org',
  },
  {
    id: 'kol-11',
    name: 'Manish A. Shah',
    institution: 'Weill Cornell Medicine / NewYork-Presbyterian Hospital',
    city: 'New York',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 95,
    engagementTier: 'Tier 1',
    productAlignment: ['ziihera'],
    recentInteractions: 9,
    publications: 180,
    focusAreas: ['Gastroesophageal Cancer ASCO Guidelines', 'Zanidatamab Bispecific Mechanism', 'HER2/PD-L1/MSI/CLDN18.2 Biomarker Framework', 'GATSBY Trial'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Engage as a guideline advisory partner; ASCO Guideline Co-Chair role for GEA means engaging him on Ziihera label positioning now directly shapes 2026 ASCO gastroesophageal guidelines.',
    email: 'mas9313@med.cornell.edu',
  },
  {
    id: 'kol-12',
    name: 'Kohei Shitara',
    institution: 'National Cancer Center Hospital East',
    city: 'Kashiwa',
    country: 'Japan',
    region: 'Asia-Pacific',
    specialty: 'GI Medical Oncology',
    influenceScore: 97,
    engagementTier: 'Tier 1',
    productAlignment: ['ziihera'],
    recentInteractions: 6,
    publications: 300,
    focusAreas: ['HERIZON-GEA-01 Named PI', 'DESTINY-Gastric01/02', 'HER2 Intratumoral Heterogeneity', 'Asian HER2+ GEA Populations'],
    conferenceAppearances: 12,
    recommendedStrategy: 'Engage as primary international scientific collaborator; essential for Japan PMDA filings and Asia-Pacific label expansion; Highly Cited Researcher designation amplifies every Ziihera endorsement.',
    email: 'kshitara@east.ncc.go.jp',
  },
  {
    id: 'kol-13',
    name: 'Jaffer A. Ajani',
    institution: 'MD Anderson Cancer Center',
    city: 'Houston',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['ziihera'],
    recentInteractions: 8,
    publications: 350,
    focusAreas: ['NCCN GEA Committee Chair', 'HER2/PD-L1/MSI/CLDN18.2 Four-Biomarker Framework', 'CheckMate 649', 'Gastric/Esophageal Phase II/III Trials'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Engage proactively on NCCN guideline inclusion strategy; an advisory relationship is likely the most direct path to Category 1/2A Ziihera GEA guideline listing.',
    email: 'jajani@mdanderson.org',
  },
  {
    id: 'kol-14',
    name: 'Milind M. Javle',
    institution: 'MD Anderson Cancer Center',
    city: 'Houston',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['ziihera'],
    recentInteractions: 10,
    publications: 200,
    focusAreas: ['HER2+ Biliary Tract Cancer', 'FGFR2 / IDH1 / HER2 Targeted BTC Therapy', 'MyPathway BTC Trial', 'Lancet Oncology HER2+ BTC Framework'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Engage as advisory board anchor for the BTC indication; editorial leadership at CCA News Online is a direct channel to the BTC specialist community nationwide.',
    email: 'mjavle@mdanderson.org',
  },
  {
    id: 'kol-15',
    name: 'Rachna T. Shroff',
    institution: 'University of Arizona Cancer Center',
    city: 'Tucson',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 82,
    engagementTier: 'Tier 2',
    productAlignment: ['ziihera'],
    recentInteractions: 8,
    publications: 120,
    focusAreas: ['SWOG 1815 National PI (BTC)', 'HERIZON-GEA-01 Co-investigator', 'Zanidatamab BTC & GEA Trials', 'Multimarker Targeted Therapy in CCA'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Engage for speaker bureau and cooperative group partnership; SWOG network reaches community GI oncologists at scale, critical for Ziihera BTC launch messaging beyond academic centers.',
    email: 'rshroff@arizona.edu',
  },
  {
    id: 'kol-16',
    name: 'Lipika Goyal',
    institution: 'Stanford Cancer Center / Stanford University School of Medicine',
    city: 'Stanford',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 81,
    engagementTier: 'Tier 2',
    productAlignment: ['ziihera'],
    recentInteractions: 7,
    publications: 100,
    focusAreas: ['HERIZON-BTC-01 Final OS Data', 'FGFR2 Fusion-Targeted Therapy', 'Lancet Oncology HER2+ BTC Co-author', 'IDH1-Targeted CCA'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Engage as West Coast regional scientific spokesperson; ACS Researcher of the Year recognition and FGFR2 trial leadership give her credibility well beyond the HER2 subgroup.',
    email: 'lgoyal@stanford.edu',
  },
  {
    id: 'kol-17',
    name: 'R. Kate Kelley',
    institution: 'UCSF Helen Diller Family Comprehensive Cancer Center',
    city: 'San Francisco',
    country: 'USA',
    region: 'North America',
    specialty: 'GI Medical Oncology',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['ziihera'],
    recentInteractions: 6,
    publications: 150,
    focusAreas: ['HCC & Biliary Tract Cancer Trials', 'Lancet Oncology HER2+ BTC Co-author', 'Immunotherapy Combinations in BTC', 'ASCO GI / ESMO Presenter'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Engage for ASCO GI-focused medical education programs; the Kelley/Javle/Goyal triad collectively co-authored the foundational HER2+ BTC framework paper, making all three natural joint spokespeople for Ziihera\'s BTC indication.',
    email: 'kate.kelley@ucsf.edu',
  },
];
