// Predictive Signals — Jazz demo.
// Social media signal velocity is the headline capability.
// Signals blend X/LinkedIn/ResearchGate monitoring with MSL and congress feeds.

export const PREDICTIVE_SIGNALS = [
  {
    id: 'ps-1',
    agent: 'ARIA',
    signal: 'Social signal velocity spike: #H3K27M on X (+310% in 14 days)',
    currentState: 'Following ASCO 2025 abstract drops, mentions of H3 K27M and dordaviprone surged 310% on X. Dominant voices: 7 neuro-oncology KOLs + 3 patient advocacy accounts. Tone: 82% positive framing around Modeyso efficacy.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Deploy rapid MSL response team to amplify accurate clinical narrative on X/LinkedIn. Prepare citable real-world evidence thread for KOL repost.',
    suggestedAction: { label: 'Open in ARIA', path: '/congress' },
  },
  {
    id: 'ps-2',
    agent: 'LUCA',
    signal: 'KOL alignment gap detected: Dr. S. Merchant (public vs. private)',
    currentState: 'LUCA detects a divergence between Dr. Merchant\'s public LinkedIn posts (cautious on Modeyso in pediatric DMG) and two recent MSL interactions where she expressed positive enthusiasm. Alignment score dropped from 78 → 49.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'medium',
    requiredAction: 'Schedule scientific exchange to understand her unmet evidence needs. Provide pediatric DMG data package before she publishes a perspective piece.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
  {
    id: 'ps-3',
    agent: 'NOVA',
    signal: 'Ziihera HER2 conversation share rising on LinkedIn ahead of GEC data',
    currentState: 'Zanidatamab is mentioned in 41% of HER2+ GEC LinkedIn discussions among GI oncologists — up from 18% 90 days ago. Trastuzumab deruxtecan (Enhertu) still leads at 67%. Sentiment toward zanidatamab bispecific mechanism: 74% favorable.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'high',
    requiredAction: 'Surface bispecific differentiation content into social channels ahead of GEC launch. Brief GI KOLs with mechanism one-pager for organic amplification.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-4',
    agent: 'LUCA',
    signal: '3 emerging neuro-oncology digital influencers crossed the 5K follower threshold',
    currentState: 'Three neuro-oncologists (combined 18K X followers) have posted ≥4 times about H3 K27M mutation testing in the past 30 days. None are on the current MSL engagement list. Posting cadence and engagement rates are trending toward tier-2 KOL territory.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Add all three to LUCA watch list. Prioritize outreach for two with academic affiliation. Consider inviting to digital advisory board.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
  {
    id: 'ps-5',
    agent: 'NOVA',
    signal: 'RWE evidence gap amplified in patient advocacy social channels',
    currentState: 'National Brain Tumor Society and Pediatric Brain Tumor Foundation communities on Facebook and X are actively discussing gaps in pediatric Modeyso dosing data. Combined reach: ~120K patient and caregiver followers. Mentions spiked after a patient-shared journal club post.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'high',
    requiredAction: 'Engage NBTS and PBTF medical liaison contacts. Offer RWE update webinar for patient community. Monitor for misinformation and prepare response protocol.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
];
